#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  3 14:34:01 2019

@author: andreaagostini
"""

a = -1
b = -1
c = -1

while a != 0 and b != 0 and c != 0:
    a = int(input())
    b = int(input())
    c = int(input())
    
    if b == a + 4 and c == a + 7:
        print('maggiore')
    else:
        print('nope')

print('bye bye')
